spring:
  kafka:
    bootstrap-servers: kafka-0:9092,kafka-1:9092,kafka-2:9092
    producer:
      acks: all
      linger-ms: 20
      batch-size: 16384
      compression-type: snappy
server:
  port: 8090